// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBIf7qW0RwSacxBDSRjlXKM6qSSarSD9k',
    appId: '1:694457330631:web:cd591a68f5aaa8f74a07e2',
    messagingSenderId: '694457330631',
    projectId: 'kurumtakipapp',
    authDomain: 'kurumtakipapp.firebaseapp.com',
    storageBucket: 'kurumtakipapp.firebasestorage.app',
    measurementId: 'G-S495PEGTN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdGY3kGvVfABlrDK7nwS6NdWICH44TPww',
    appId: '1:694457330631:android:d5e2431fb853508f4a07e2',
    messagingSenderId: '694457330631',
    projectId: 'kurumtakipapp',
    storageBucket: 'kurumtakipapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF8Sam76qa1SOz8fA3nYMtfgshOJzTpzo',
    appId: '1:694457330631:ios:dfc0c4e7735acfe34a07e2',
    messagingSenderId: '694457330631',
    projectId: 'kurumtakipapp',
    storageBucket: 'kurumtakipapp.firebasestorage.app',
    iosBundleId: 'com.mebs.kurumtakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF8Sam76qa1SOz8fA3nYMtfgshOJzTpzo',
    appId: '1:694457330631:ios:dfc0c4e7735acfe34a07e2',
    messagingSenderId: '694457330631',
    projectId: 'kurumtakipapp',
    storageBucket: 'kurumtakipapp.firebasestorage.app',
    iosBundleId: 'com.mebs.kurumtakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBIf7qW0RwSacxBDSRjlXKM6qSSarSD9k',
    appId: '1:694457330631:web:0e2189f0703976614a07e2',
    messagingSenderId: '694457330631',
    projectId: 'kurumtakipapp',
    authDomain: 'kurumtakipapp.firebaseapp.com',
    storageBucket: 'kurumtakipapp.firebasestorage.app',
    measurementId: 'G-JR8HMRE20L',
  );

}